### ISSUE TITLE
Short description of the workflow

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/building-shiny-apps-workflow#19]
https://github.com/ThinkR-open/building-shiny-apps-workflow/blob/master/workflow.Rmd

The idea there is to have a kind of one chapter cheatsheet about the whole workflow. So each subpart should summarize the steps of the workflow.

**Comment by statnmap** [comment]
Some ideas

#### Prototype

- "Rmd first" allows to show intermediate steps to clients using your personal HTML or PDF template (cf {pdreport}) so that they can choose the data exploration direction, graphs and table formats. For the developer, it is easier to propose multiple designs of graphs on a Rmd.

#### Package

- Once a step is clean and fixed, the developer can embed as a function and test a small example. 
- Then move the code to the function directory ("R" folder, for R packages) and add documentation of each parameter and the small example code
- "Rmd first" also allows to write the objective of the step with real words, what enters and what exits the function, so that tests can be thought even before writing the code. That would be a "test first" approach.
    + Tests can directly be added to the test directory ("tests" folder, for R packages)
- As the core of the function code has moved to the function and tests directory, the Rmd only keeps the examples on how to use the function.

#### Modularize

- If the project is important, it may require multiple developers. Everything is driven by a git repository. Each developer works on is own part of the project. Separating the work into multiple Rmarkdown simplify collaboration and code merge. If you already face a "git conflict", you know why we separate things as much as possible. Of course, a good communication between developers also help.

#### Deploy

- Finalize the package. Propose internal reports, vignettes as presentation of the deliverables. Deploy HTML documentation on server if required (Rstudio Connect, Rstudio server, ...). Deploy the package on machines, servers if needed.
- Propose training to use the package built and explain how to maintain or continue to develop it

## Special case for Shiny Applications

### A Shiny Application is in a package

Our working method requires Shiny Applications to be 

"Build, Integrate, Transfer, Explore"
The "4 steps" method I think it sums it up well:

- Prototyping: we read the specifications, we make an app prototype, we validate the design and functionality
        "Rmd first"
 - Package: we create a package with all the benefits of packaging an app. Package == dependency, documentation, versioning, test, continuous integration, all the way
- Modularize: we work in module with all that it brings for the collaborative and not to be bothered to call 15 buttons "ok" differently. Modularize == modules, versioning, teamwork, all the way
- Deploy, Production

If we could find a word other than "Modularize" we could have something like:
    "The 4 steps shiny app: Prototype, Package, Podule, Production"

**Comment by statnmap** [comment]
This one has been merged. We can close it.
